# Generated by Django 3.2.9 on 2023-01-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(14, 26, 56, 568716), verbose_name='appointment time'),
        ),
    ]
