# Generated by Django 3.2.9 on 2023-01-18 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(15, 2, 13, 163608), verbose_name='appointment time'),
        ),
    ]
