# Generated by Django 3.2.9 on 2023-01-18 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(15, 7, 1, 613071), verbose_name='appointment time'),
        ),
    ]
